basePath: /
definitions:
  github_com_ICOMP-UNC_newworld-FlorSchroder_internal_models.Register:
    properties:
      email:
        example: example@example.com
        type: string
      password:
        example: password123
        type: string
      username:
        example: johndoe
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:3000
info:
  contact:
    email: you@example.com
  description: This is a sample server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /analytics/average-delivery-time:
    get:
      consumes:
      - application/json
      description: get average delivery time data
      produces:
      - application/json
      responses:
        "200":
          description: GetAverageDeliveryTime
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get average delivery time
      tags:
      - analytics
  /analytics/most-expensive-sale:
    get:
      consumes:
      - application/json
      description: get most expensive sale data
      produces:
      - application/json
      responses:
        "200":
          description: GetMostExpensiveSale
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get most expensive sale
      tags:
      - analytics
  /auth/register:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: User registration details
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/github_com_ICOMP-UNC_newworld-FlorSchroder_internal_models.Register'
      produces:
      - application/json
      responses:
        "201":
          description: User added
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Bad server
          schema:
            type: string
      summary: Register
      tags:
      - auth
  /market:
    get:
      consumes:
      - application/json
      description: get market summary data
      produces:
      - application/json
      responses:
        "200":
          description: GetSummaryMarket
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get market summary
      tags:
      - market
swagger: "2.0"
